# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

target 'example' do
    use_frameworks!
    inhibit_all_warnings!

    pod 'SwipeMenu', :path => '../'

end


