language: swift
os: osx
osx_image: xcode9.3
branches:
  only:
    - master
env:
  matrix:
    - TEST_TYPE=iOS
script:
- |
    xcodebuild -project SwipeMenu.xcodeproj -target SwipeMenu  -configuration Release
